Repository Coinsence/coinsence-monorepo, pull requests merged in 2019-06, with the labels that each got.

#36 add only members account to space
  lib/http/apps/migrate.js
Labels: kredits-1

#37 fix typo + update api doc
  docs/apidoc/api_data.js
  docs/apidoc/api_data.json
  docs/apidoc/api_project.js
  docs/apidoc/api_project.json
  lib/http/apps/migrate.js
Labels: kredits-1

#38 fix coin minting when migrating
  lib/http/apps/migrate.js
Labels: kredits-1

#39 Sequiential wallet creation
  lib/http/apps/wallet.js
Labels: kredits-1

#40 sequential wallet creation
  lib/http/apps/wallet.js
Labels: kredits-1

#44 Remove wallet key encryption
  lib/http/utils/create-wallet.js
  lib/http/utils/load-wallet.js
  scripts/recover-funds.js
Labels: kredits-3

#46 Fix load wallet
  lib/http/utils/create-wallet.js
  lib/http/utils/load-wallet.js
Labels: kredits-1

#45 Save deployed DAO info
  .gitignore
  docs/apidoc/api_data.js
  docs/apidoc/api_data.json
  docs/apidoc/api_project.js
  docs/apidoc/api_project.json
  lib/addresses/CoinsenceKit.json
  lib/http/_apidoc.js
  lib/http/apps/dao.js
  lib/http/utils/load-dao.js
  lib/http/utils/save-dao.js
  lib/kit.js
Labels: kredits-2
